spring:
  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



  datasource:
    url: jdbc:mysql://localhost/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  data:
    elasticsearch:
      properties:
        transport.tcp.connect_timeout: 120s
      cluster-nodes: 127.0.0.1:9300




